name: game_consign_assessment
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_local_notifications: ^17.1.2
  rxdart: ^0.28.0
  sqflite: ^2.3.3+1
  toastification: ^2.0.0
  loading_animation_widget: ^1.2.1
  overlay_loading_progress: ^1.0.1
  cupertino_icons: ^1.0.6
  workmanager: ^0.5.2
  shared_preferences: ^2.2.3
  path_provider: ^2.1.3
  simple_infinite_scroll: ^1.1.2
  intl: ^0.19.0
  date_field: ^5.2.1
  flutter_osm_plugin: ^1.0.5
  geolocator: ^12.0.0
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
